// <auto-generated />
using System;
using BloodNetwork.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodNetwork.Migrations
{
    [DbContext(typeof(BloodNetworkContext))]
    [Migration("20230401165213_BloodCategory")]
    partial class BloodCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BloodNetwork.Models.Adress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("AdressName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Adress");
                });

            modelBuilder.Entity("BloodNetwork.Models.BloodCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BloodID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("ClinicID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BloodID");

                    b.HasIndex("CategoryID");

                    b.ToTable("BloodCategory");
                });

            modelBuilder.Entity("BloodNetwork.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("BloodNetwork.Models.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("City");
                });

            modelBuilder.Entity("BloodNetwork.Models.Clinic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("AdressID")
                        .HasColumnType("int");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Phone")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("AdressID");

                    b.HasIndex("CityID");

                    b.HasIndex("DoctorID");

                    b.ToTable("Clinic");
                });

            modelBuilder.Entity("BloodNetwork.Models.Doctor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("BloodNetwork.Models.BloodCategory", b =>
                {
                    b.HasOne("BloodNetwork.Models.Clinic", "Blood")
                        .WithMany("BloodCategories")
                        .HasForeignKey("BloodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodNetwork.Models.Category", "Category")
                        .WithMany("BloodCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blood");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BloodNetwork.Models.Clinic", b =>
                {
                    b.HasOne("BloodNetwork.Models.Adress", "Adress")
                        .WithMany("Clinics")
                        .HasForeignKey("AdressID");

                    b.HasOne("BloodNetwork.Models.City", "City")
                        .WithMany("Clinics")
                        .HasForeignKey("CityID");

                    b.HasOne("BloodNetwork.Models.Doctor", "Doctor")
                        .WithMany("Clinics")
                        .HasForeignKey("DoctorID");

                    b.Navigation("Adress");

                    b.Navigation("City");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("BloodNetwork.Models.Adress", b =>
                {
                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("BloodNetwork.Models.Category", b =>
                {
                    b.Navigation("BloodCategories");
                });

            modelBuilder.Entity("BloodNetwork.Models.City", b =>
                {
                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("BloodNetwork.Models.Clinic", b =>
                {
                    b.Navigation("BloodCategories");
                });

            modelBuilder.Entity("BloodNetwork.Models.Doctor", b =>
                {
                    b.Navigation("Clinics");
                });
#pragma warning restore 612, 618
        }
    }
}
